<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_pageHeading</name>
   <tag></tag>
   <elementGuidId>68df2762-3c47-408a-8b4a-0ce60b3aa389</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.heading</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
