<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddMoreOrders</name>
   <tag></tag>
   <elementGuidId>8fa39385-d697-43ba-8cac-08b786e7f097</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.action-link</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
