<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>QuickOrdersBox</name>
   <tag></tag>
   <elementGuidId>55294a1b-c43e-44e1-b195-1d3118d7d20a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.quick-order-box</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
