<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>QuicOrderTab</name>
   <tag></tag>
   <elementGuidId>237a4fd7-cda5-4d57-aa1d-a90bf62c1be4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[aria-controls=&quot;quick-order&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
