<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_comments</name>
   <tag></tag>
   <elementGuidId>d2122565-91fc-4dc3-a2cb-fa4448b79e1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comments</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
