import helpers.ComputerAndRegisterPageHelpers
import helpers.GeneralHelpers
import helpers.HeaderHelpers

GeneralHelpers.initScenario()
HeaderHelpers.hoveringTagsAndFormLink()
ComputerAndRegisterPageHelpers.clickingOnComputerAndRegisterLink()