<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cardName</name>
   <tag></tag>
   <elementGuidId>cdc6323b-d248-4626-a655-878e27cf1bff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
