<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_continue</name>
   <tag></tag>
   <elementGuidId>5860fbe7-64da-45cc-afc1-4f670c62a23f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[onclick=&quot;goToCheckout()&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
