<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_orderPo</name>
   <tag></tag>
   <elementGuidId>927659ca-a6f2-4717-8abd-d1a0bb3664c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#po</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
